name: Judge

on: pull_request

jobs:
  judge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: EtherOJ/EtherJudger@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
